#include <VectorPhysics/Aircraft/AircraftForces.hpp>


double AircraftForces::getDrag(double rho, glm::vec3 velocity, double refA, double Cd, double Cl, double wingspan, double e)
{
    double speed = glm::length(velocity);

    // Parasite drag
    double pDrag = 0.5 * rho * speed * speed * Cd * refA;

    // Aspect ratio
    double AR = wingspan * wingspan / refA;

    // Induced drag coefficient
    double Cdi = (Cl * Cl) / (M_PI * AR * e);

    // Induced drag force
    double iDrag = 0.5 * rho * speed * speed * refA * Cdi;

    return pDrag + iDrag;
}

double AircraftForces::getLift(double rho, glm::vec3 velocity, double wingA, double Cl)
{
    wingArea = wingA;
    Clift = Cl;
    // Return the lift generated by the wings
    double speed = glm::length(velocity);
    return Cl * (1.0 / 2.0) * rho * std::pow(speed, 2) * wingA;
}
